/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProblemDetails,
  UpdateUserPreferencesDto,
  UserPreferencesDto,
} from '../models';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    UpdateUserPreferencesDtoFromJSON,
    UpdateUserPreferencesDtoToJSON,
    UserPreferencesDtoFromJSON,
    UserPreferencesDtoToJSON,
} from '../models';

export interface UpdateUserPreferencesRequest {
    updateUserPreferencesDto?: UpdateUserPreferencesDto;
}

/**
 * 
 */
export class UserPreferencesApi extends runtime.BaseAPI {

    /**
     */
    async getUserPreferencesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPreferencesDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/users/me/preferences`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPreferencesDtoFromJSON(jsonValue));
    }

    /**
     */
    async getUserPreferences(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPreferencesDto> {
        const response = await this.getUserPreferencesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateUserPreferencesRaw(requestParameters: UpdateUserPreferencesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPreferencesDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerJWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/users/me/preferences`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserPreferencesDtoToJSON(requestParameters.updateUserPreferencesDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPreferencesDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateUserPreferences(requestParameters: UpdateUserPreferencesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPreferencesDto> {
        const response = await this.updateUserPreferencesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
