/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddAssetValueDto
 */
export interface AddAssetValueDto {
    /**
     * 
     * @type {number}
     * @memberof AddAssetValueDto
     */
    value: number;
    /**
     * 
     * @type {Date}
     * @memberof AddAssetValueDto
     */
    timeStamp: Date;
}

/**
 * Check if a given object implements the AddAssetValueDto interface.
 */
export function instanceOfAddAssetValueDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "timeStamp" in value;

    return isInstance;
}

export function AddAssetValueDtoFromJSON(json: any): AddAssetValueDto {
    return AddAssetValueDtoFromJSONTyped(json, false);
}

export function AddAssetValueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAssetValueDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'timeStamp': (new Date(json['timeStamp'])),
    };
}

export function AddAssetValueDtoToJSON(value?: AddAssetValueDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'timeStamp': (value.timeStamp.toISOString()),
    };
}

