/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddAlertDto
 */
export interface AddAlertDto {
    /**
     * 
     * @type {number}
     * @memberof AddAlertDto
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof AddAlertDto
     */
    originAssetName: string;
    /**
     * 
     * @type {string}
     * @memberof AddAlertDto
     */
    currency: string;
}

/**
 * Check if a given object implements the AddAlertDto interface.
 */
export function instanceOfAddAlertDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "originAssetName" in value;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function AddAlertDtoFromJSON(json: any): AddAlertDto {
    return AddAlertDtoFromJSONTyped(json, false);
}

export function AddAlertDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAlertDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'originAssetName': json['originAssetName'],
        'currency': json['currency'],
    };
}

export function AddAlertDtoToJSON(value?: AddAlertDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'originAssetName': value.originAssetName,
        'currency': value.currency,
    };
}

