/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserDto
 */
export interface AddUserDto {
    /**
     * 
     * @type {string}
     * @memberof AddUserDto
     */
    userId: string;
}

/**
 * Check if a given object implements the AddUserDto interface.
 */
export function instanceOfAddUserDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function AddUserDtoFromJSON(json: any): AddUserDto {
    return AddUserDtoFromJSONTyped(json, false);
}

export function AddUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function AddUserDtoToJSON(value?: AddUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
    };
}

