/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlertDto
 */
export interface AlertDto {
    /**
     * 
     * @type {number}
     * @memberof AlertDto
     */
    alertId?: number;
    /**
     * 
     * @type {number}
     * @memberof AlertDto
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof AlertDto
     */
    originAssetName?: string;
    /**
     * 
     * @type {string}
     * @memberof AlertDto
     */
    currency?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AlertDto
     */
    active?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlertDto
     */
    originAssetType?: string;
}

/**
 * Check if a given object implements the AlertDto interface.
 */
export function instanceOfAlertDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AlertDtoFromJSON(json: any): AlertDto {
    return AlertDtoFromJSONTyped(json, false);
}

export function AlertDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlertDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'alertId': !exists(json, 'alertId') ? undefined : json['alertId'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'originAssetName': !exists(json, 'originAssetName') ? undefined : json['originAssetName'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'active': !exists(json, 'active') ? undefined : json['active'],
        'originAssetType': !exists(json, 'originAssetType') ? undefined : json['originAssetType'],
    };
}

export function AlertDtoToJSON(value?: AlertDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'alertId': value.alertId,
        'value': value.value,
        'originAssetName': value.originAssetName,
        'currency': value.currency,
        'active': value.active,
        'originAssetType': value.originAssetType,
    };
}

