/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetValueDto
 */
export interface AssetValueDto {
    /**
     * 
     * @type {string}
     * @memberof AssetValueDto
     */
    assetIdentifier: string;
    /**
     * 
     * @type {number}
     * @memberof AssetValueDto
     */
    value: number;
    /**
     * 
     * @type {Date}
     * @memberof AssetValueDto
     */
    timeStamp: Date;
}

/**
 * Check if a given object implements the AssetValueDto interface.
 */
export function instanceOfAssetValueDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "assetIdentifier" in value;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "timeStamp" in value;

    return isInstance;
}

export function AssetValueDtoFromJSON(json: any): AssetValueDto {
    return AssetValueDtoFromJSONTyped(json, false);
}

export function AssetValueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetValueDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assetIdentifier': json['assetIdentifier'],
        'value': json['value'],
        'timeStamp': (new Date(json['timeStamp'])),
    };
}

export function AssetValueDtoToJSON(value?: AssetValueDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assetIdentifier': value.assetIdentifier,
        'value': value.value,
        'timeStamp': (value.timeStamp.toISOString()),
    };
}

