/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OperationType = {
    Update: 'Update',
    Set: 'Set'
} as const;
export type OperationType = typeof OperationType[keyof typeof OperationType];


export function OperationTypeFromJSON(json: any): OperationType {
    return OperationTypeFromJSONTyped(json, false);
}

export function OperationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationType {
    return json as OperationType;
}

export function OperationTypeToJSON(value?: OperationType | null): any {
    return value as any;
}

