/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchUser
 */
export interface PatchUser {
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchUser
     */
    email?: string | null;
}

/**
 * Check if a given object implements the PatchUser interface.
 */
export function instanceOfPatchUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchUserFromJSON(json: any): PatchUser {
    return PatchUserFromJSONTyped(json, false);
}

export function PatchUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': !exists(json, 'fullName') ? undefined : json['fullName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function PatchUserToJSON(value?: PatchUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'email': value.email,
    };
}

