/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPreferencesDto
 */
export interface UserPreferencesDto {
    /**
     * 
     * @type {string}
     * @memberof UserPreferencesDto
     */
    preferenceCurrency: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserPreferencesDto
     */
    weeklyReports: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserPreferencesDto
     */
    alertsOnEmail: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserPreferencesDto
     */
    isDefault: boolean;
}

/**
 * Check if a given object implements the UserPreferencesDto interface.
 */
export function instanceOfUserPreferencesDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "preferenceCurrency" in value;
    isInstance = isInstance && "weeklyReports" in value;
    isInstance = isInstance && "alertsOnEmail" in value;
    isInstance = isInstance && "isDefault" in value;

    return isInstance;
}

export function UserPreferencesDtoFromJSON(json: any): UserPreferencesDto {
    return UserPreferencesDtoFromJSONTyped(json, false);
}

export function UserPreferencesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferencesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'preferenceCurrency': json['preferenceCurrency'],
        'weeklyReports': json['weeklyReports'],
        'alertsOnEmail': json['alertsOnEmail'],
        'isDefault': json['isDefault'],
    };
}

export function UserPreferencesDtoToJSON(value?: UserPreferencesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'preferenceCurrency': value.preferenceCurrency,
        'weeklyReports': value.weeklyReports,
        'alertsOnEmail': value.alertsOnEmail,
        'isDefault': value.isDefault,
    };
}

