/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetDto } from './AssetDto';
import {
    AssetDtoFromJSON,
    AssetDtoFromJSONTyped,
    AssetDtoToJSON,
} from './AssetDto';

/**
 * 
 * @export
 * @interface UserAssetDto
 */
export interface UserAssetDto {
    /**
     * 
     * @type {AssetDto}
     * @memberof UserAssetDto
     */
    asset: AssetDto;
    /**
     * 
     * @type {number}
     * @memberof UserAssetDto
     */
    originValue: number;
    /**
     * 
     * @type {number}
     * @memberof UserAssetDto
     */
    userCurrencyValue: number;
}

/**
 * Check if a given object implements the UserAssetDto interface.
 */
export function instanceOfUserAssetDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "asset" in value;
    isInstance = isInstance && "originValue" in value;
    isInstance = isInstance && "userCurrencyValue" in value;

    return isInstance;
}

export function UserAssetDtoFromJSON(json: any): UserAssetDto {
    return UserAssetDtoFromJSONTyped(json, false);
}

export function UserAssetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAssetDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'asset': AssetDtoFromJSON(json['asset']),
        'originValue': json['originValue'],
        'userCurrencyValue': json['userCurrencyValue'],
    };
}

export function UserAssetDtoToJSON(value?: UserAssetDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset': AssetDtoToJSON(value.asset),
        'originValue': value.originValue,
        'userCurrencyValue': value.userCurrencyValue,
    };
}

