/* tslint:disable */
/* eslint-disable */
/**
 * ZPI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: all
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletDto
 */
export interface WalletDto {
     /**
     * 
     * @type {number}
     * @memberof WalletDto
     */
    value: number;
    /**
     * 
     * @type {Date}
     * @memberof WalletDto
     */
    dateStamp: Date;
}

/**
 * Check if a given object implements the WalletDto interface.
 */
export function instanceOfWalletDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "timeStamp" in value;

    return isInstance;
}

export function WalletDtoFromJSON(json: any): WalletDto {
    return WalletDtoFromJSONTyped(json, false);
}

export function WalletDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': json['value'],
        'dateStamp': (new Date(json['dateStamp'])),
    };
}

export function WalletDtoToJSON(value?: WalletDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'timeStamp': (value.dateStamp.toISOString()),
    };
}

